### PR TITLE
Transition python2 scripts to python3.

### PR DESCRIPTION
**Pull request by troycurtisjr**
- Update add.py, install_remove.py, and mintlocale.py to support
  python3.
- Use conditional imports and the codecs module to still allow python2
  to be used if needed.
- Update shebang lines to use /usr/bin/python3.
- Addresses Issue #48

### CODE REVIEW

**Comment by clefebvre** [comment]
Everything seems to be working quite well.. I'm seeing a little regression though:

`LANGUAGE=C sudo usr/lib/linuxmint/mintlocale/install_remove.py`

capture du 2017-10-18 16-05-24

See the top item in the treeview.

**Comment by troycurtisjr** [comment]
Ah man! I'll take a look and see if I can duplicate and provide an updated
PR. Which distro/version are you running it on?

**Comment by troycurtisjr** [comment]
Never mind, I found it.  The update to using `check_output()` could end up with an extra empty line at the end that needed to be handled.

**Comment by clefebvre** [comment]
Thanks :)

**Pull request merged**
